# Generated by Django 2.0.1 on 2018-01-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(max_length=1500)),
                ('url_redirect_to', models.CharField(max_length=1500)),
                ('shortened_url_ending', models.CharField(max_length=7)),
                ('shortened_url_full', models.CharField(max_length=57)),
            ],
        ),
    ]
